### ISSUE TITLE
用OC重写了一遍，但是有问题。

### ISSUE THREAD

**Issue by TheWalkingDead1024** [DanisFabric/RainbowNavigation#1]
我把你的代码用OC重新写了一遍，但是发现运行效果很差，根本不能用，难道OC和Swift机制还不一样？

**Comment by DanisFabric** [comment]
一样的，我最开始就是用OC写的。之后才是用Swift重构了一遍。但是目前APP里面仍然使用的OC版本，运行良好

**Comment by TheWalkingDead1024** [comment]
不好意思哈，是我自己的问题。我再想问的是，如果navigationcontroller里面的viewcontrollers里面某一个是需要transparent，其余不需要。比方说这个需要transparent叫做BVC，在需要transparent场景切换的情况下（从BVC去push一个页面，或者从BVC去pop自己这个页面BVC）可以用你写的代码来实现这个效果，那普通的页面切换呢。第一种情况，针对你的demo里面的MainTableVC(名字我都简写，这个其实是MainTableViewController)，从MainTableVC去push到ColorTableVC，我如果在MainTable不设置颜色（显示的就是原生NavigationController的颜色），ColorTableVC设置红色，页面切换会有异常，这是不是说某个页面有设置颜色的需求，与这个页面有push或pop关系的VC都需要设置颜色，以此类推，那岂不是整个栈内的VC都需要设置颜色？第二种情况，从MainTableVC（同样不设置颜色）切换到TransparentTalbeVC（设置为透明），在这两个页面来回切换navigationBar也会有异常，当然这个问题和第一种情况是一样的，我是觉得这里有特殊需求（navigationBar颜色或透明）的页面会影响到别的普通页面。我想能做到的就是某个页面有特殊navigationBar颜色设置需求，就仅在这个VC做修改，别的普通VC不需要依赖于有这个有特殊需求的VC。[HHNavigationController-Demo](https://github.com/shuoshi/HHNavigationController-Demo)这个实现方式和你的不一样，它是做了一个假的navigationBar加到了VC的View里面，效果也和你的不一样，但是他有个比较好的地方就是能做到仅在有特殊需求的VC里面做一些设置就可以了。栈内别的VC不需要依赖于这个特殊需求的VC，这样用起来感觉挺爽的。我不喜欢他的地方就是需要继承，我不喜欢继承，当然我也可以搞category，swizzle一些系统方法（这个做法很不好），再就是你的效果我蛮喜欢的，而且实现的方式遵循着苹果所提倡的场景切换动画来实现的，它那个实现方式有点hack，搞一个假的navigationbar，而且还遍历navigationBar的subview去隐藏某个图片。说了很多，如果大神你有解决方法，请不吝赐教，非常感谢。我说的地方可能有不对的地方请见谅。谢谢。

**Comment by DanisFabric** [comment]
1. 通过df_setBackgroundColor 来设置navigationBar的背景色
2. 如果你push一个viewcontroller进来，实现RainbowColorSource协议之后。一个方法负责`In`，一个方法负责`Out`，我觉得这个层次的设计ViewController已经能够对Color进行自管理了。

但有一个缺陷的地方就是，强制要求NavigationBar是tranlucent ＝ true
