### ISSUE TITLE
混编，RainbowNavigation.swift 中的代理方法无法触发

### ISSUE THREAD

**Issue by siegrainwong** [DanisFabric/RainbowNavigation#2]
现在通过打断点发现`RainbowNavigation.swift`中的`UINavigationControllerDelegate`相关的代理方法的没有触发过，自然数据源方法也不会触发。

我自己也写了个 Swift 文件在项目中测试，同样无法触发 UINavigationController 对应的代理方法(e.g.  navigationViewController willShowViewController)。

求救...我觉得应该是我混编姿势有问题...

**Comment by siegrainwong** [comment]
囧，我用法有问题。。
在navigationcontroller初始化的时候就把它挂上去了，这样不会有效果。

**Comment by DanisFabric** [comment]
贴代码看看
