### ISSUE TITLE
调用了 wireToNavigationController 后，设置下个视图 hideBottomBarWhenPushed = YES 会导致 Tab bar 瞬间消失

### ISSUE THREAD

**Issue by siegrainwong** [DanisFabric/RainbowNavigation#3]
当前视图层次为 Tab Bar Controller -> Navigation Controller -> View Controllers

正常的效果为tabbar 随着上级视图一起消失，现在的效果是push的瞬间tabbar就没了。

**Comment by DanisFabric** [comment]
这个是我自定义的动画隐藏tabBar的代码写错了，我现在把这个改了，发了1.1.0的版本上来。你更新一下就好
